#!/usr/bin/env python3
"""Generate the rule about an agent's tree having been moved out from under a collection.

The catalogue records, per agent, the environment variables that change where that agent
keeps its data or whether it keeps it at all. That field exists because a collection keyed
on a default path finds nothing on a host where the tree was moved, and finding nothing is
indistinguishable from an agent that was never used.

The rule that reads those variables out of a shell profile therefore has to name them, and
there are seventy-odd across thirty-one agents. Writing them into a rule file by hand would
be the exact defect this repository keeps finding in itself: a statement about the
catalogue, written once, next to a catalogue that then moves. So the rule is generated, the
way the collection rules and the artifact documentation are, and CI fails when the
committed file drifts from the catalogue.

What is left out, and why. The platform's own variables are excluded: HOME, USERPROFILE,
TMPDIR, PATH and the freedesktop ones. They are in the catalogue because an agent's path
is computed from them, which is true and is what the collector needs to know, but they are
exported in ordinary profiles for ordinary reasons and a rule that fired on them would fire
on most developer machines. Their absence is stated in the generated file rather than left
for a reader to notice.

Written to stay inside this directory's Python 3.8 lint target (see .ruff.toml), even
though importing the analyzer package means it only runs on 3.14 or newer.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from agentforensics.catalog import load_catalogue, resolve_text  # noqa: E402

CATALOG_DIR = REPO_ROOT / "catalog"
TARGET = REPO_ROOT / "rules" / "collection_integrity" / "AFX-COLLECTIONINTEGRITY-001.yaml"

# Variables that belong to the platform rather than to an agent. See the module docstring:
# they are in the catalogue for a good reason and they are not evidence about an agent.
GENERIC = frozenset(
    {
        "HOME",
        "PATH",
        "TMPDIR",
        "USERPROFILE",
        "XDG_CACHE_HOME",
        "XDG_CONFIG_HOME",
        "XDG_DATA_HOME",
        "XDG_RUNTIME_DIR",
        "XDG_STATE_HOME",
    }
)

HEADER = """# GENERATED by scripts/gen_relocation_rule.py from catalog/. Do not edit.
#
# The names below are the environment variables the catalogue records as changing where an
# agent keeps its data, or whether it keeps it. They are generated because there are {count}
# of them across {agents} agents and because a list of catalogue facts copied into a rule file
# is a list that stops being true without anybody noticing.
#
# Deliberately excluded, and this is the whole of the exclusion: {generic}. Those are the
# platform's own variables. An agent's path is computed from them, which is why the
# catalogue carries them, but they are exported in ordinary profiles for ordinary reasons
# and a rule that matched them would fire on most developer machines.
"""


def variables(catalogue: object) -> "list[tuple[str, str, str]]":
    """Every agent-specific relocation variable, once each, with an agent and its effect."""
    seen = {}
    for agent in catalogue.agents:  # type: ignore[attr-defined]
        for override in agent.env_overrides or ():
            if override.name in GENERIC or override.name in seen:
                continue
            seen[override.name] = (override.name, agent.agent, resolve_text(override.effect)[0])
    return [seen[name] for name in sorted(seen)]


def render(catalogue: object) -> str:
    found = variables(catalogue)
    names = "|".join(name for name, _, _ in found)
    agents = len({agent for _, agent, _ in found})
    example, example_agent, _ = next(
        (item for item in found if item[0].endswith("CONFIG_DIR")), found[0]
    )
    header = HEADER.format(count=len(found), agents=agents, generic=", ".join(sorted(GENERIC)))
    body = f"""id: AFX-COLLECTIONINTEGRITY-001
pack: collection_integrity
title: An agent was configured to write somewhere else, or not at all
severity: medium
description: >
  A shell profile, or the environment an agent ran in, exports a variable the catalogue
  records as changing where that agent keeps its data or whether it keeps it. What was
  collected from the default path is therefore not necessarily what that agent wrote.
rationale: >
  This rule is about the case rather than about the endpoint, which is why it exists at
  all. Every other finding says something happened; this one says a part of the collection
  may be answering the wrong question. An agent whose home was moved leaves nothing at the
  path a collection searched, and nothing found there reads exactly like an agent that was
  never used. The variable is usually set for an ordinary reason, so this is not a
  suspicion about anybody: it is an instruction to go back and collect the path the
  variable names before concluding anything from an empty result.
applies_to:
  kinds: [config.snapshot, prompt.history, command.exec, unparsed.record]
match:
  field: event_text
  # [^\\S\\n] rather than \\s: the text a rule searches is the record's leaves one per line,
  # and \\s matches a newline, so a name at the end of one line and an unrelated value at
  # the start of the next would otherwise match as an assignment.
  regex: '\\b({names})[^\\S\\n]*[=:][^\\S\\n]*\\S'
tags:
  - collection-integrity
  - relocated-tree
false_positives:
  - >-
    A variable set to the location the agent uses anyway, which changes nothing and is
    common in a profile that spells out a default.
  - >-
    A mention in a configuration file or a script that explains the variable rather than
    setting it, since the rule searches the text a record holds. A question about the
    variable in a conversation is out of scope by kind and cannot reach this rule.
  - >-
    A variable that was exported after the period under investigation, since a profile
    says what is in force and not when a line was added to it.
references:
  - https://code.claude.com/docs/en/troubleshoot-install.md
tests:
  - name: an agent home exported in a shell profile
    match: true
    event:
      kind: config.snapshot
      agent: {example_agent}
      payload: {{key: "export:{example}", text: "export {example}=/opt/agents/elsewhere"}}
  - name: the same variable in a command somebody ran
    match: true
    event:
      kind: command.exec
      agent: {example_agent}
      payload:
        commands: [{{command: "{example}=/tmp/scratch claude"}}]
  - name: an unrelated variable
    match: false
    event:
      kind: config.snapshot
      agent: {example_agent}
      payload: {{key: "export:EDITOR", text: "export EDITOR=vim"}}
  - name: the variable named with no value
    match: false
    event:
      kind: config.snapshot
      agent: {example_agent}
      payload: {{key: "export:{example}", text: "# {example} is unset here"}}
"""
    return header + body


def main(argv: "list[str] | None" = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed file differs")
    args = parser.parse_args(argv)

    catalogue = load_catalogue(CATALOG_DIR)
    text = render(catalogue)
    found = variables(catalogue)

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != text:
            diff = difflib.unified_diff(
                current.splitlines(), text.splitlines(), "committed", "generated", lineterm=""
            )
            print("\n".join(diff))
            print("gen-relocation-rule: the committed rule is stale, run without --check")
            return 1
        print("gen-relocation-rule: current, {0} variable(s)".format(len(found)))
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(text, encoding="utf-8")
    print("gen-relocation-rule: wrote {0} with {1} variable(s)".format(TARGET.name, len(found)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
